# fly.toml app configuration file generated for twitchclipfinder on 2024-09-28T20:54:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twitchclipfinder'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = './Dockerfile'

[processes]
  app = "bin/rails server"
  worker = "bundle exec sidekiq"

[deploy]
  strategy = "immediate"
  release_command = "bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  grace_period = "20s"
  interval = "10s"
  timeout = "2s"
  method = "get"
  path = "/health_check"
  protocol = "http"
  restart_limit = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1