
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password


development:
  <<: *default
  database: favorite_clip_finder

test:
  <<: *default
  database: favorite_clip_finder_test


production:
  <<: *default
  database: favorite_clip_finder_production
  username: <%= ENV["MYAPP_DATABASE_USER"] %>
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
