# config/sidekiq_schedule.yml

:concurrency: 5

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 * * * *"   # 毎時0分に実行
      class: FetchTwitchClipsJob
      queue: default

    update_streamers_job:
      cron: "0 * * * *"   # 毎時0分に実行
      class: UpdateStreamersJob
      queue: default