# config/sidekiq.yml

:concurrency: 5

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_japanese_streamers_job:
      cron: "0 */3 * * *"   # 3時間ごとに実行
      class: FetchJapaneseStreamersJob
      queue: default
