:concurrency: 5

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 */12 * * *"   # 12時間ごとに実行
      class: FetchTwitchClipsJob
      queue: default

    update_streamers_job:
      cron: "0 */12 * * *"   # 12時間ごとに実行
      class: UpdateStreamersJob
      queue: default