:concurrency: 5

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 */12 * * *"       # 12時間ごとに実行
      class: FetchTwitchClipsJob
      queue: default
      description: "12時間ごとにTwitchクリップを取得するジョブ"