scheduler:
  schedule:
    fetch_japanese_streamers_job:
      cron: "0 */2 * * *" # 2時間おきに実行
      class: FetchJapaneseStreamersJob
      queue: default
    fetch_twitch_clips_job:
      cron: "0 0 * * *"
      class: FetchTwitchClipsJob
      queue: default