# config/sidekiq_schedule.yml

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 0,12 * * *"   # 毎日0時と12時に実行
      class: FetchTwitchClipsJob
      queue: default

    fetch_japanese_streamers_job:
      cron: "0 0,12 * * *"   # 毎日0時と12時に実行
      class: FetchJapaneseStreamersJob
      queue: default