# config/sidekiq.yml

:concurrency: 5

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_japanese_streamers_job:
      cron: "0 0 1 1 *"   # 毎年1月1日0時に実行
      class: FetchJapaneseStreamersJob
      queue: default

    fetch_twitch_clips_job:
      cron: "0 0 1 1 *"   # 毎年1月1日0時に実行
      class: FetchTwitchClipsJob
      queue: default
