:concurrency: 5

:queues:
  - default
  - critical
  - mailer

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 0 * * *"
      class: FetchTwitchClipsJob
      queue: default

    fetch_japanese_streamers_job:
      cron: "0 */2 * * *"
      class: FetchJapaneseStreamersJob
      queue: default