:concurrency: 2

:queues:
  - default
  - critical

scheduler:
  schedule:
    fetch_twitch_clips_job:
      cron: "0 * * * *"   # 毎日5時間ごとに実行
      class: FetchTwitchClipsJob
      queue: default

    update_streamers_job:
      cron: "0 * * * *"   # 毎時0分に実行
      class: UpdateStreamersJob
      queue: default
